In [1]:
for i in range(3):
    for j in range(4):
        arr.random.random()
for i in range(2):
    for j in range(2):
        
        

SyntaxError: invalid syntax (1267135616.py, line 1)

In [21]:
import numpy as np
x=np.arange(6)
print(x)
y=x.reshape([2,3])
print(y)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [31]:
#10
a = np.arange(1, 13).reshape(3, 4)
print(a)
print(a[2][3])
print(a[-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[ 9 10 11 12]


In [47]:
#15.Create a 1-D array of 15 elements. Use np.split() to split it into three equal parts, and print each part.
a=np.arange(15)

x1,x2,x3=np.split(a,[3,5])
print(x1)
print(x2)
print(x3)

[0 1 2]
[3 4]
[ 5  6  7  8  9 10 11 12 13 14]


In [31]:
#14.	Create two 2x3 arrays of random integers. Concatenate them (a) vertically using np.vstack() and np.concatenate(axis=0), and (b) horizontally using np.hstack() and np.concatenate(axis=1). Confirm both methods give the same result.
import numpy as np
np.random.seed(0)
arr1=np.random.randint(0,21,(2,3))
arr2=np.random.randint(0,21,(2,3))
print(arr1)
print(arr2)
#hor
horizontal=np.hstack([arr1,arr2])
h_concat=np.concatenate([arr1,arr2],axis=1)
print(h_concat)
print(horizontal)
vertical=np.vstack([arr1,arr2])
print(vertical)

[[12 15  0]
 [ 3  3  7]]
[[ 9 19 18]
 [ 4  6 12]]
[[12 15  0  9 19 18]
 [ 3  3  7  4  6 12]]
[[12 15  0  9 19 18]
 [ 3  3  7  4  6 12]]
[[12 15  0]
 [ 3  3  7]
 [ 9 19 18]
 [ 4  6 12]]


In [15]:
#Structured Arrays
student_dtype=np.dtype([('name','U10'),('sem','i4'),('cgpa','f8')])
students=np.zeros(3,dtype=student_dtype)

students['name']=['sid','raj','ram']
students['sem']=[5,5,5]
students['cgpa']=[9.8,8.8,9.9]
print(students)
print("names of the students:",students['name'])
print("cgpa of the students : ",students['cgpa'])
print(students[2])
print("student with cgpa less than 9.0 : ",students[students['cgpa']<9.0]['name'])
student_record=students.view(np.recarray)
print(student_record.cgpa)

[('sid', 5, 9.8) ('raj', 5, 8.8) ('ram', 5, 9.9)]
names of the students: ['sid' 'raj' 'ram']
cgpa of the students :  [9.8 8.8 9.9]
('ram', 5, 9.9)
student with cgpa less than 9.0 :  ['raj']
[9.8 8.8 9.9]


In [5]:
import numpy as np
books_dtype=np.dtype([('title','U30'),('author','U20'),('price','f8')])
books=np.zeros(4,dtype=books_dtype)
books['title']=['atomic habbit','master mind','33 stratagy of war','laws of human nature']
books['author']=['James Clear','Maria Konnikova',' Robert Greene','Robert Greene']
books['price']=['230','990','1242','3453']
print(books[2])
print(books)
print(books['title'])

('33 stratagy of war', ' Robert Greene', 1242.)
[('atomic habbit', 'James Clear',  230.)
 ('master mind', 'Maria Konnikova',  990.)
 ('33 stratagy of war', ' Robert Greene', 1242.)
 ('laws of human nature', 'Robert Greene', 3453.)]
['atomic habbit' 'master mind' '33 stratagy of war' 'laws of human nature']


In [17]:
#dictinory method
np.dtype({
    'names':{'name','age','weight'},
    'formats':{'U10','i4','f8'}
})
np.dtype({
    'names':{'name','age','weight'},
    'formats':{(np.str_,10),int,np.float32}
})
np.dtype([
    ('name','s10'),('age','i4'),('weight','f8')])
np.dtype('s10,i4,f8') 

TypeError: 'set' object is not subscriptable

In [25]:
tp=np.dtype([
    ('id','i8'),('mat','f8',(3,3))
])
x=np.zeros(1,dtype=tp)
print(x[0])
print(x['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
data_rec=data.view(np.recarray)
print(data_rec.age)
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

NameError: name 'data' is not defined

In [1]:
import pandas as pd

In [25]:
data=pd.Series({2:'a',3:'b'})
print(data)
d1=pd.Series([10,20,30,40])
print(d1)
d2=pd.Series([10,20,30,40],index=[7,8,9,9])
print(d2)
print(pd.Series({2:'a',3.1:'b','s':12}))

2    a
3    b
dtype: object
0    10
1    20
2    30
3    40
dtype: int64
7    10
8    20
9    30
9    40
dtype: int64
2       a
3.1     b
s      12
dtype: object


In [29]:
df1=pd.DataFrame(population,column=['population'])
df2=pd.DataFrame(np.random.rand(3,2),column=['foo','bar'],index=['a','b','c'])
print(df1)
print(df2)

df3=pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])
print(df3)
#d=[
    {'a' :i,'b':2*i} for i in range(10)]
#df4=pd.DataFrame(d)

IndentationError: unexpected indent (19525974.py, line 9)

In [ ]:
data=np.array(['sid
np.dtype([
    ('name','s10'),('age','i4'),('weight','f8')])

In [31]:
import numpy as np
import pandas as pd
books_dtype=np.dtype([('title','U30'),('author','U20'),('price','f8')])
books=np.zeros(4,dtype=books_dtype)
books['title']=['atomic habbit','master mind','33 stratagy of war','laws of human nature']
books['author']=['James Clear','Maria Konnikova',' Robert Greene','Robert Greene']
books['price']=['230','990','1242','3453']

df=pd.DataFrame(books)
print(df)

                  title           author   price
0         atomic habbit      James Clear   230.0
1           master mind  Maria Konnikova   990.0
2    33 stratagy of war    Robert Greene  1242.0
3  laws of human nature    Robert Greene  3453.0


In [47]:
ind=pd.Index([2,3,5,7,11])
print(ind)
# ind[3]=10 error caz its immutable
print(ind.size,ind.shape,ind.ndim,ind.dtype)
print(ind[1])
print(ind[::2])
print(ind[1:4:2])

indA=pd.Index([1,2,3,4,5,6])
indB=pd.Index([10,20,30,40,5,60])

print(indA & indB)
print(indA | indB)
print(indA ^ indB)

Index([2, 3, 5, 7, 11], dtype='int64')
5 (5,) 1 int64
3
Index([2, 5, 11], dtype='int64')
Index([3, 7], dtype='int64')
Index([0, 0, 2, 0, 5, 4], dtype='int64')
Index([11, 22, 31, 44, 5, 62], dtype='int64')
Index([11, 22, 29, 44, 0, 58], dtype='int64')


In [57]:
#28
d=pd.Series([45, 67, 89, 23, 56])
print(d.index)
print(d.values)
print(d)

RangeIndex(start=0, stop=5, step=1)
[45 67 89 23 56]
0    45
1    67
2    89
3    23
4    56
dtype: int64


In [71]:
#29
cty=pd.Series([1000,45886,6847416549,54545,5841],index=['Mumbai', 'Delhi', 'Bengaluru', 'Chennai', 'Kolkata'])
print(cty)
print(cty['Bengaluru'])
print(cty['Delhi' :'Chennai' ])

Mumbai             1000
Delhi             45886
Bengaluru    6847416549
Chennai           54545
Kolkata            5841
dtype: int64
6847416549
Delhi             45886
Bengaluru    6847416549
Chennai           54545
dtype: int64


In [73]:
#31
area=pd.Series([148990,45886,6847416549,54545,5841],index=['Mumbai', 'Delhi', 'Bengaluru', 'Chennai', 'Kolkata'])
population=pd.Series([12450,321000,68040,75000,50000],index=['Mumbai', 'Delhi', 'Bengaluru', 'Chennai', 'Kolkata'])
